REM -----------------------------------------------------------------------
REM --- Comparing engine using NDLModelTest -------------------------------
REM --- Version for multi-folder outputs ----------------------------------
REM -----------------------------------------------------------------------

REM Following variables must be already defined:
REM _NMTDRIVER - path to the NMT engine
REM _PROCESSEDFOLDER - Root of all folders generated by any type of processing
REM _CMP_IN - Folder where to get the input data from (originally _OUTFOLDER)
REM _CMP_OUT - Folder where NMT saves the comparing results; a list of subfolders expected
REM _CMPNMT_TESTQFOLDER - Folder where are the comapring TestQs are taken from
REM _SUBTASKSLISTFILE - File with actual list of processed tickets (generated during AET run)
REM _LOGFILE - Common Log file

echo ^>Entering CMPNMT_MULTIFOLDER.bat>>%_LOGFILE%
echo ^>Entering CMPNMT_MULTIFOLDER.bat

if not exist %_CMP_OUT% md %_CMP_OUT%

echo Starting NDL Model Test comparing...
echo Starting NDL Model Test comparing...>>%_LOGFILE%

SETLOCAL EnableDelayedExpansion 

REM Get the real output folder names
for /F "skip=1" %%i in (%_SUBTASKSLISTFILE%) do (
    set _THIS_TASKNAME=%%i
    set _THIS_TESTQFILE=!_THIS_TASKNAME!.testq
    echo TestQ: !_THIS_TESTQFILE!
    echo TestQ: !_THIS_TESTQFILE! >>%_LOGFILE%
    
    REM Assembly TestQs using the real output folder names
    echo INPUT=%_CMP_IN%\!_THIS_TASKNAME! > %_CMPNMT_TESTQFOLDER%\ActualTestQ.txt
    type %_CMPNMT_TESTQFOLDER%\Common1.txt >> %_CMPNMT_TESTQFOLDER%\ActualTestQ.txt
    echo REFERENCE=%_REFFOLDER%\!_THIS_TASKNAME! >> %_CMPNMT_TESTQFOLDER%\ActualTestQ.txt
    type %_CMPNMT_TESTQFOLDER%\Common2.txt >> %_CMPNMT_TESTQFOLDER%\ActualTestQ.txt
    copy %_CMPNMT_TESTQFOLDER%\ActualTestQ.txt %_CMPNMT_TESTQFOLDER%\!_THIS_TESTQFILE!

    REM echo %_CMPNMT_TESTQFOLDER%\!_THIS_TESTQFILE!, %_CMP_OUT%\!_THIS_TASKNAME!_NMTCompare.log
    REM Run the NMT Compare engine
    %_NMTDRIVER% -testq %_CMPNMT_TESTQFOLDER%\!_THIS_TESTQFILE! -outputroot=%_PROCESSEDFOLDER% -run -compare -recurse -cleanout > %_CMP_OUT%\!_THIS_TASKNAME!_NMTCompare.log
    %_NMTREPORT% -testq %_CMPNMT_TESTQFOLDER%\!_THIS_TESTQFILE! -outputroot=%_PROCESSEDFOLDER% -reportroot=%_PROCESSEDFOLDER% -report > %_CMP_OUT%\!_THIS_TASKNAME!_NMTReport.log
    )

echo Comparing done.
echo Comparing done. >>%_LOGFILE%
EXIT /B 0
