REM -----------------------------------------------------------------------
REM --- COMMON PARAMETERS ----------------------------------------------
REM --- Parameters common for all testers ---------------------------------
REM -----------------------------------------------------------------------

REM Automated Esko Tester name and location
set _AETFOLDER=%_GLOBALHELPERSFOLDER%\AutomatedEskoTester
set _AETCOMMONNAME=%_AETFOLDER%\AETLauncher
set _jsxSCRIPT=%_AETFOLDER%\AutomatedEskoTester.jsx

REM Define local script folders 
set _HELPERSFOLDER=%_ROOT%\_Helpers
set _SCRIPTSFOLDER=%_HELPERSFOLDER%\Scripts\Specific
set _PARAMETERSFOLDER=%_HELPERSFOLDER%\Scripts\Parameters

REM Common Parameter Configurators
set P_NMTCompare=%_PARAMETERSFOLDER%\Parameters-NMTCompare.bat
set P_EGCompare=%_PARAMETERSFOLDER%\Parameters-EGCompare.bat
set P_NMTTrap-PDFCompare=%_PARAMETERSFOLDER%\Parameters-NMTTrap-PDFCompare.bat
set P_NMTApplyMarks=%_PARAMETERSFOLDER%\Parameters-NMTApplyMarks.bat
set P_NMTTrap=%_PARAMETERSFOLDER%\Parameters-NMTTrap.bat
set P_Statistics=%_PARAMETERSFOLDER%\Parameters-Statistics.bat
set P_Transform=%_PARAMETERSFOLDER%\Parameters-Transform.bat
set P_Mailer=%_PARAMETERSFOLDER%\Parameters-Mailer.bat

REM Common Source files folder for NDL PDF export/import testers
set _COMMONSOURCEFOLDER=%_UNC_ROOT_SERVER%\CommonSource

REM Common Helpers
set _G_VBSCRIPTSFOLDER=%_GLOBALSCRIPTSFOLDER%\VBScripts
set G_vbsSUM=%_G_VBSCRIPTSFOLDER%\sum.vbs

set "_MAKEONTOP=python %_GLOBALSCRIPTSFOLDER%\generate_ontop_files.py"

set G_STARTLOGGING=%_GLOBALSCRIPTSFOLDER%\STARTLOGGING.bat
set G_GETBUILDNUMBERS=%_GLOBALSCRIPTSFOLDER%\GETBUILDNUMBERS.bat
set G_SETTIMESTAMP=%_GLOBALSCRIPTSFOLDER%\SETTIMESTAMP.bat
set G_TIMESTAMP=%_GLOBALSCRIPTSFOLDER%\TIMESTAMP.bat
set G_UPDATEALLPLUGINS=%_GLOBALSCRIPTSFOLDER%\UPDATEALLPLUGINS.bat
set G_CLEANUP_PROCESSED=%_GLOBALSCRIPTSFOLDER%\CLEANUP_PROCESSED.bat
set G_CLEANUP_COMPARED=%_GLOBALSCRIPTSFOLDER%\CLEANUP_COMPARED.bat
set G_CLEANUP_REFERENCE=%_GLOBALSCRIPTSFOLDER%\CLEANUP_REFERENCE.bat
set G_NMTCOMPARE=%_GLOBALSCRIPTSFOLDER%\CMPNMT.bat
set G_NMTSCOMPARE=%_GLOBALSCRIPTSFOLDER%\CMPNMTS.bat
set G_EGCOMPARE=%_GLOBALSCRIPTSFOLDER%\CMPEGC.bat
set G_KILLILL=%_GLOBALSCRIPTSFOLDER%\KILLILL.bat
set G_RESTART_NMT=%_GLOBALSCRIPTSFOLDER%\RESTART_NMT.bat
set G_EXPORTLOGSPROCESSING=%_GLOBALSCRIPTSFOLDER%\EXPORTLOGSPROCESSING.bat
rem set G_STATCOMMON=%_GLOBALSCRIPTSFOLDER%\STATCOMMON.bat
set G_STAT=%_GLOBALSCRIPTSFOLDER%\STAT.bat
set G_TRANSFORM=%_GLOBALSCRIPTSFOLDER%\TRANSFORM.bat
set G_SENDREPORT=%_GLOBALSCRIPTSFOLDER%\MAILER.bat
set G_GETSAFEDATE=%_GLOBALSCRIPTSFOLDER%\GETSAFEDATE.bat
set G_REPORTING=%_GLOBALSCRIPTSFOLDER%\REPORTER.bat
set G_COMPARER=%_GLOBALSCRIPTSFOLDER%\COMPARER.bat
set G_PROCESSOR=%_GLOBALSCRIPTSFOLDER%\PROCESSOR.bat
set G_RECOVERYCLEANER=%_GLOBALSCRIPTSFOLDER%\RECOVERYCLEANER.bat
set G_ARCHIVE_PROCESSED=%_GLOBALSCRIPTSFOLDER%\ARCHIVE_PROCESSED.bat
set G_ARCHIVE_COMPARED=%_GLOBALSCRIPTSFOLDER%\ARCHIVE_COMPARED.bat
set G_ARCHIVE_OTHERS=%_GLOBALSCRIPTSFOLDER%\ARCHIVE_OTHERS.bat
set G_ARCHIVE_REFERENCE=%_GLOBALSCRIPTSFOLDER%\ARCHIVE_REFERENCE.bat
set G_ARCHIVE_CLEANER=%_GLOBALSCRIPTSFOLDER%\ARCHIVE_CLEANER.bat

REM XSLT common folder
set _G_XSLTFOLDER=%_GLOBALHELPERSFOLDER%\XSL

REM HTML common folder
set _G_HTMLFOLDER=%_GLOBALHELPERSFOLDER%\HTML
set _STAT_HTMLHEADER=%_G_HTMLFOLDER%\HTMLHeader.txt
set _STAT_HTMLTABHEADER=%_G_HTMLFOLDER%\HTMLTabHeader.txt
set _STAT_HTMLTABFOOTER=%_G_HTMLFOLDER%\HTMLTabFooter.txt
set _STAT_HTMLFOOTER=%_G_HTMLFOLDER%\HTMLFooter.txt

REM Automatic Esko Tester common
set _vbsAiStart=%_AETCOMMONNAME%-AiStart.vbs

REM Update Marks - default NO
set _UPDATEMARKS=NO

REM Indication of autoupdate skipping
set "_WARNING_UPDATESKIPPED= "

REM Common folder names for outputs
set _PROCESSED_FOLDERNAME=Processed
set _PROCESSEDFOLDER=%_ROOT%\%_PROCESSED_FOLDERNAME%
set _OUTFOLDER=%_PROCESSEDFOLDER%\%_TOPIC%
set _CMP_FOLDERNAME=Compared
set _PDFCMP_FOLDERNAME=PDFCompared
set _STAT_SUMMARYFILE=%_GLOBALHELPERSFOLDER%\BatchTestingSummary\%_TOPIC%_Summary.txt

REM Common folder names archives
set _ARCHIVEFOLDER=%_ROOT%\Archive
REM Number of files, which should not be deleted during archive cleanup
set _KEEPALIVE=10


REM Log folder
set _LOGFOLDER=%_HELPERSFOLDER%\Logging

REM Global TMP folders
set _GTMP=%_HELPERSFOLDER%\TMP
if not exist %_GTMP% MD %_GTMP%
set _FINDTMPFILE=%_GTMP%\find.tmp
set _DATATMPFILE=%_GTMP%\data.tmp



