REM -----------------------------------------------------------------------
REM --- Comparing engine using NDLModelTest -------------------------------
REM --- Single/Multifolder version ----------------------------------------
REM -----------------------------------------------------------------------

REM Following variables must be already defined:
REM --- Global variables ---
REM _LOGFILE - Common log file name

REM --- Tester specific variables
REM _NMTDRIVER - path to the NMT engine
REM _PROCESSEDFOLDER - Root of all folders generated by any type of processing
REM _CMP_IN - Folder where to get the input data from (originally _OUTFOLDER)
REM _CMP_OUT - Folder where NMT saves the comparing results
REM _CMPNMT_TESTQFOLDER - Folder where are the comapring TestQs are taken from
REM _SUBTASKSLISTFILE - File with actual list of processed tickets (generated during AET run)
REM _MULTIFOLDER_CMP - General switch indicating the output mode multifolder/flat

echo ^>Entering CMPNMT.bat /%_TOPIC%/>>%_LOGFILE%
echo ^>Entering CMPNMT.bat /%_TOPIC%/

if not exist %_CMP_OUT% md %_CMP_OUT%

echo Starting NDL Model Test comparing...
echo Starting NDL Model Test comparing...>>%_LOGFILE%

set _NMTTASKSFILE=Common2.txt
if "%_UPDATEMARKS%"=="YES" (set _NMTTASKSFILE=Common3.txt) 
    
REM Replace dangerous UNC server with 
CALL SET _DOS_CMP_OUT=%%_CMP_OUT:%_UNC_ROOT_SERVER%=%_DOS_ROOT_SERVER%%%
CALL SET _DOS_CMP_IN=%%_CMP_IN:%_UNC_ROOT_SERVER%=%_DOS_ROOT_SERVER%%%

SETLOCAL EnableDelayedExpansion 

if "%_MULTIFOLDER_CMP%" EQU "YES" (

    REM Initialize Pre-compare log file
    echo Pre-Compare rendering collected logs: > %_PRECMPLOGFILE%
    REM Initialize Compare log file
    echo Compare collected logs: > %_CMPLOGFILE%

    REM Get the real output folder names
    for /F "skip=1" %%i in (%_SUBTASKSLISTFILE%) do (
        set _THIS_TASKNAME=%%i
        set _THIS_TESTQFILE=%_CMPNMT_TESTQFOLDER%\!_THIS_TASKNAME!.testq
        echo TestQ: !_THIS_TESTQFILE!
        echo TestQ: !_THIS_TESTQFILE! >>%_LOGFILE%
        
        REM Assembly TestQs using the real output folder names
		echo Assembling testq to %_CMPNMT_TESTQFOLDER%\ActualTestQ.txt
		echo ---
		echo INPUT=%_CMP_IN%\!_THIS_TASKNAME! 
        echo Content of: %_CMPNMT_TESTQFOLDER%\Common1.txt - 
		type %_CMPNMT_TESTQFOLDER%\Common1.txt
        echo REFERENCE=%_REFFOLDER%\!_THIS_TASKNAME! 
        echo Content of: %_CMPNMT_TESTQFOLDER%\%_NMTTASKSFILE% 
        type %_CMPNMT_TESTQFOLDER%\%_NMTTASKSFILE% 
		echo ---

        echo INPUT=%_CMP_IN%\!_THIS_TASKNAME! > %_CMPNMT_TESTQFOLDER%\ActualTestQ.txt
        type %_CMPNMT_TESTQFOLDER%\Common1.txt >> %_CMPNMT_TESTQFOLDER%\ActualTestQ.txt
        echo REFERENCE=%_REFFOLDER%\!_THIS_TASKNAME! >> %_CMPNMT_TESTQFOLDER%\ActualTestQ.txt
        type %_CMPNMT_TESTQFOLDER%\%_NMTTASKSFILE% >> %_CMPNMT_TESTQFOLDER%\ActualTestQ.txt
        copy "%_CMPNMT_TESTQFOLDER%\ActualTestQ.txt" "!_THIS_TESTQFILE!"

        if not exist %_CMP_OUT%\!_THIS_TASKNAME!\log md "%_CMP_OUT%\!_THIS_TASKNAME!\log"
        if not exist %_CMP_OUT%\!_THIS_TASKNAME!\diff md "%_CMP_OUT%\!_THIS_TASKNAME!\diff"
        
        REM Run the NMT Compare engine
        echo %_NMTDRIVER% -testq !_THIS_TESTQFILE! -outputroot=%_PROCESSEDFOLDER% -run -compare -recurse -cleanout 
        echo %_NMTREPORT% -testq !_THIS_TESTQFILE! -outputroot=%_PROCESSEDFOLDER% -reportroot=%_PROCESSEDFOLDER% -report 
        echo %_NMTDRIVER% -testq !_THIS_TESTQFILE! -outputroot=%_PROCESSEDFOLDER% -run -compare -recurse -cleanout  >>%_LOGFILE%
        echo %_NMTREPORT% -testq !_THIS_TESTQFILE! -outputroot=%_PROCESSEDFOLDER% -reportroot=%_PROCESSEDFOLDER% -report  >>%_LOGFILE%

		call %G_TIMESTAMP%

        %_NMTDRIVER% -testq !_THIS_TESTQFILE! -outputroot=%_PROCESSEDFOLDER% -run -compare -recurse -cleanout > %_CMP_OUT%\!_THIS_TASKNAME!_NMTCompare.log
        %_NMTREPORT% -testq !_THIS_TESTQFILE! -outputroot=%_PROCESSEDFOLDER% -reportroot=%_PROCESSEDFOLDER% -report > %_CMP_OUT%\!_THIS_TASKNAME!_NMTReport.log
        
		call %G_TIMESTAMP%

        REM Collect the log files
        for /F "usebackq delims=" %%f in (`dir /b %_CMP_OUT%\!_THIS_TASKNAME!\log\*.log`) do (
            set _THIS_LOGFILE=%%f
            echo --- File : !_THIS_LOGFILE! >>%_PRECMPLOGFILE%
            type "%_CMP_OUT%\!_THIS_TASKNAME!\log\!_THIS_LOGFILE!" >>%_PRECMPLOGFILE%
            )
        echo. >>%_CMPLOGFILE%
        echo *** TestQ: !_THIS_TASKNAME! >>%_CMPLOGFILE%
        type %_CMP_OUT%\!_THIS_TASKNAME!\diff\cmp.log >>%_CMPLOGFILE%
        
        
    )
) else (
    REM Assembly TestQ using the Topic name
    set _THIS_TASKNAME=%_TOPIC%
    set _THIS_TESTQFILE=%_CMPNMT_TESTQFOLDER%\!_THIS_TASKNAME!.testq
    echo TestQ: !_THIS_TESTQFILE!
    
	echo Assembling testq to %_CMPNMT_TESTQFOLDER%\ActualTestQ.txt
	echo ---
	echo INPUT=%_CMP_IN% 
	echo Content of: %_CMPNMT_TESTQFOLDER%\Common1.txt 
	type %_CMPNMT_TESTQFOLDER%\Common1.txt 
	echo REFERENCE=%_REFFOLDER% 
	echo Content of: %_CMPNMT_TESTQFOLDER%\%_NMTTASKSFILE%
	type %_CMPNMT_TESTQFOLDER%\%_NMTTASKSFILE%
	echo ---

    echo INPUT=%_CMP_IN% > %_CMPNMT_TESTQFOLDER%\ActualTestQ.txt
    type %_CMPNMT_TESTQFOLDER%\Common1.txt >> %_CMPNMT_TESTQFOLDER%\ActualTestQ.txt
    echo REFERENCE=%_REFFOLDER% >> %_CMPNMT_TESTQFOLDER%\ActualTestQ.txt
    type %_CMPNMT_TESTQFOLDER%\%_NMTTASKSFILE% >> %_CMPNMT_TESTQFOLDER%\ActualTestQ.txt
    copy "%_CMPNMT_TESTQFOLDER%\ActualTestQ.txt" "!_THIS_TESTQFILE!"
  
    REM REM Run the NMT Compare engine
    if not exist %_CMP_OUT%\!_THIS_TASKNAME!\log md %_CMP_OUT%\!_THIS_TASKNAME!\log
    if not exist %_CMP_OUT%\!_THIS_TASKNAME!\diff md %_CMP_OUT%\!_THIS_TASKNAME!\diff

    echo %_NMTDRIVER% -testq !_THIS_TESTQFILE! -outputroot=%_DOS_PROCESSEDFOLDER% -run -compare -recurse -cleanout
    echo %_NMTREPORT% -testq !_THIS_TESTQFILE! -outputroot=%_PROCESSEDFOLDER% -reportroot=%_PROCESSEDFOLDER% -report
    echo %_NMTDRIVER% -testq !_THIS_TESTQFILE! -outputroot=%_DOS_PROCESSEDFOLDER% -run -compare -recurse -cleanout >>%_LOGFILE%
    echo %_NMTREPORT% -testq !_THIS_TESTQFILE! -outputroot=%_PROCESSEDFOLDER% -reportroot=%_PROCESSEDFOLDER% -report >>%_LOGFILE%

	call %G_TIMESTAMP%
    
    %_NMTDRIVER% -testq !_THIS_TESTQFILE! -outputroot=%_DOS_PROCESSEDFOLDER% -run -compare -recurse -cleanout > %_CMP_OUT%\!_THIS_TASKNAME!_NMTCompare.log
    %_NMTREPORT% -testq !_THIS_TESTQFILE! -outputroot=%_PROCESSEDFOLDER% -reportroot=%_PROCESSEDFOLDER% -report > %_CMP_OUT%\!_THIS_TASKNAME!_NMTReport.log
    
	call %G_TIMESTAMP%

    REM Collect the log files
    for /F "usebackq delims=" %%f in (`dir /b '%_CMP_OUT%\!_THIS_TASKNAME!\log\*.log'`) do (
        set _THIS_LOGFILE=%%f
        echo --- File : !_THIS_LOGFILE! >>%_PRECMPLOGFILE%
        type "%_CMP_OUT%\!_THIS_TASKNAME!\log\!_THIS_LOGFILE!" >>%_PRECMPLOGFILE%
        )
    type %_CMP_OUT%\!_THIS_TASKNAME!\diff\cmp.log >>%_CMPLOGFILE%
)

echo %_MAKEONTOP% %_CMP_OUT% %_REFFOLDER%
echo %_MAKEONTOP% %_CMP_OUT% %_REFFOLDER%  >>%_LOGFILE%

%_MAKEONTOP% %_CMP_OUT% %_REFFOLDER%

echo Comparing done.
echo Comparing done. >>%_LOGFILE%

echo %_TOPIC% Pre-compare Render Log File: %_PRECMPLOGFILE%
echo %_TOPIC% Compare Log File: %_CMPLOGFILE%

echo %_TOPIC% Pre-compare Render Log File: %_PRECMPLOGFILE% >>%_LOGFILE%
echo %_TOPIC% Compare Log File: %_CMPLOGFILE% >>%_LOGFILE%

EXIT /B 0
