REM -----------------------------------------------------------------------
REM --- Comparing engine using NDLModelTest Structural PDF Compare --------
REM --- Single/Multifolder version ----------------------------------------
REM -----------------------------------------------------------------------

REM Following variables must be already defined:
REM --- Global variables ---
REM _LOGFILE - Common log file name

REM --- Tester specific variables
REM _NMTDRIVER - path to the NMT engine
REM _PROCESSEDFOLDER - Root of all folders generated by any type of processing
REM _CMP_IN - Folder where to get the input data from (originally _OUTFOLDER)
REM _CMP_OUT - Folder where NMT saves the comparing results
REM _CMPNMT_TESTQFOLDER - Folder where are the comapring TestQs are taken from
REM _SUBTASKSLISTFILE - File with actual list of processed tickets (generated during AET run)
REM _MULTIFOLDER_CMP - General switch indicating the output mode multifolder/flat

echo ^>Entering CMPNMTS.bat /%_TOPIC%/>>%_LOGFILE%
echo ^>Entering CMPNMTS.bat /%_TOPIC%/

if not exist %_CMP_OUT% md %_CMP_OUT%

echo Starting NDL Model Test comparing...
echo Starting NDL Model Test comparing...>>%_LOGFILE%

rem set _NMTTASKSFILE=Common2.txt
rem if "%_UPDATEMARKS%"=="YES" (set _NMTTASKSFILE=Common3.txt) 

REM Copy the existing build collection from NMT native storage
if exist "%_NMTREPORTROOT%\builddates.xml" (copy /Y "%_NMTREPORTROOT%\builddates.xml" "%_PROCESSEDFOLDER%")
if not exist "%_NMTREPORTROOT%\%_TOPIC%_%_CMP_FOLDERNAME%" md "%_NMTREPORTROOT%\%_TOPIC%_%_CMP_FOLDERNAME%"

REM Replace dangerous UNC server with 
CALL SET _DOS_CMP_OUT=%%_CMP_OUT:%_UNC_ROOT_SERVER%=%_DOS_ROOT_SERVER%%%
CALL SET _DOS_CMP_IN=%%_CMP_IN:%_UNC_ROOT_SERVER%=%_DOS_ROOT_SERVER%%%

SETLOCAL EnableDelayedExpansion 

if "%_MULTIFOLDER_CMP%" EQU "YES" (

    REM Initialize Pre-compare log file
    echo Pre-Compare rendering collected logs: > %_PRECMPLOGFILE%
    REM Initialize Compare log file
    echo Compare collected logs: > %_CMPLOGFILE%

    REM Get the real output folder names

    for /F "skip=1" %%i in (%_SUBTASKSLISTFILE%) do (
        set _THIS_TASKNAME=%%i
        
        echo.
        echo -----------------------------------
        echo Processing !_THIS_TASKNAME!...
        echo -----------------------------------
        echo.>>%_LOGFILE%
        echo ----------------------------------->>%_LOGFILE%
        echo Processing !_THIS_TASKNAME!...>>%_LOGFILE%
        echo ----------------------------------->>%_LOGFILE%
        
        if not exist %_CMP_OUT%\!_THIS_TASKNAME!\log md "%_CMP_OUT%\!_THIS_TASKNAME!\log"
        if not exist %_CMP_OUT%\!_THIS_TASKNAME!\diff md "%_CMP_OUT%\!_THIS_TASKNAME!\diff"
		
		call %G_TIMESTAMP%
        
        echo %_NMTDRIVER% -compare -writetlog -ticket=%_CMPNMT_TESTQFOLDER%\NDLCompare.ticket -log=%_CMP_OUT%\!_THIS_TASKNAME!\log -ref=%_REFFOLDER%\!_THIS_TASKNAME! -out=%_CMP_OUT%\!_THIS_TASKNAME!\diff %_CMP_IN%\!_THIS_TASKNAME!\*.pdf
        echo %_NMTDRIVER% -compare -writetlog -ticket=%_CMPNMT_TESTQFOLDER%\NDLCompare.ticket -log=%_CMP_OUT%\!_THIS_TASKNAME!\log -ref=%_REFFOLDER%\!_THIS_TASKNAME! -out=%_CMP_OUT%\!_THIS_TASKNAME!\diff %_CMP_IN%\!_THIS_TASKNAME!\*.pdf >>%_LOGFILE%
        %_NMTDRIVER% -compare -writetlog -ticket=%_CMPNMT_TESTQFOLDER%\NDLCompare.ticket -log=%_CMP_OUT%\!_THIS_TASKNAME!\log -ref=%_REFFOLDER%\!_THIS_TASKNAME! -out=%_CMP_OUT%\!_THIS_TASKNAME!\diff %_CMP_IN%\!_THIS_TASKNAME!\*.pdf > %_CMP_OUT%\!_THIS_TASKNAME!\!_THIS_TASKNAME!_NMTCompare.log

		call %G_TIMESTAMP%

        rem Repeat without -compare to create tlog files
        rem echo %_NMTDRIVER% -ticket=%_CMPNMT_TESTQFOLDER%\NDLCompare.ticket -log=%_CMP_OUT%\!_THIS_TASKNAME!\log -ref=%_REFFOLDER%\!_THIS_TASKNAME! -out=%_CMP_OUT%\!_THIS_TASKNAME!\diff %_CMP_IN%\!_THIS_TASKNAME!\*.pdf
        rem %_NMTDRIVER% -ticket=%_CMPNMT_TESTQFOLDER%\NDLCompare.ticket -log=%_CMP_OUT%\!_THIS_TASKNAME!\log -ref=%_REFFOLDER%\!_THIS_TASKNAME! -out=%_CMP_OUT%\!_THIS_TASKNAME!\diff %_CMP_IN%\!_THIS_TASKNAME!\*.pdf

        rem Fake finished testq
        copy /Y %_HELPERSFOLDER%\testq.log %_CMP_OUT%\!_THIS_TASKNAME! > nul

        echo %_NMTREPORT% -report -outputroot=%_PROCESSEDFOLDER% -reportroot=%_PROCESSEDFOLDER% %_CMP_OUT%\!_THIS_TASKNAME!
        echo %_NMTREPORT% -report -outputroot=%_PROCESSEDFOLDER% -reportroot=%_PROCESSEDFOLDER% %_CMP_OUT%\!_THIS_TASKNAME! >>%_LOGFILE%
        %_NMTREPORT% -report -outputroot=%_PROCESSEDFOLDER% -reportroot=%_PROCESSEDFOLDER% %_CMP_OUT%\!_THIS_TASKNAME! > %_CMP_OUT%\!_THIS_TASKNAME!\!_THIS_TASKNAME!_NMTReport.log
        
        REM Replace the NDL Model Test build number by the DeskPack one
        echo xml ed -u "/testqueue/inputfile/build[@number='%_NMTBUILDNUMBER%']/@number" -v 'DP_%'%' %_CMP_OUT%\!_THIS_TASKNAME!\!_THIS_TASKNAME!.xml
        xml ed ^
        -u "/testqueue/build[@number='%_NMTBUILDNUMBER%']/@number" -v "DP_%_FULLNDLBUILDNUMBER%" ^
        -u "/testqueue/inputfile/build[@number='%_NMTBUILDNUMBER%']/@number" -v "DP_%_FULLNDLBUILDNUMBER%" ^
        %_CMP_OUT%\!_THIS_TASKNAME!\!_THIS_TASKNAME!.xml > %_STAT_XMLTMPFILE%
        
        echo copy /Y %_STAT_XMLTMPFILE% %_CMP_OUT%\!_THIS_TASKNAME!\!_THIS_TASKNAME!.xml
        copy /Y %_STAT_XMLTMPFILE% %_CMP_OUT%\!_THIS_TASKNAME!\!_THIS_TASKNAME!.xml
        
        REM Send the current report to the native NMT storage
        if not exist "%_NMTREPORTROOT%\%_TOPIC%_%_CMP_FOLDERNAME%\!_THIS_TASKNAME!" md "%_NMTREPORTROOT%\%_TOPIC%_%_CMP_FOLDERNAME%\!_THIS_TASKNAME!"
        copy /Y %_CMP_OUT%\!_THIS_TASKNAME!\!_THIS_TASKNAME!.xml "%_NMTREPORTROOT%\%_TOPIC%_%_CMP_FOLDERNAME%\!_THIS_TASKNAME!"
        if not exist "%_NMTREPORTROOT%\%_TOPIC%_%_CMP_FOLDERNAME%\!_THIS_TASKNAME!\diff" md "%_NMTREPORTROOT%\%_TOPIC%_%_CMP_FOLDERNAME%\!_THIS_TASKNAME!\diff"
        copy /y %_CMP_OUT%\!_THIS_TASKNAME!\diff\*.diff "%_NMTREPORTROOT%\%_TOPIC%_%_CMP_FOLDERNAME%\!_THIS_TASKNAME!\diff"

        REM Collect the log files
        for /F "usebackq delims=" %%f in (`dir /b %_CMP_OUT%\!_THIS_TASKNAME!\log\*.log`) do (
            set _THIS_LOGFILE=%%f
            echo --- File : !_THIS_LOGFILE! >>%_PRECMPLOGFILE%
            type "%_CMP_OUT%\!_THIS_TASKNAME!\log\!_THIS_LOGFILE!" >>%_PRECMPLOGFILE%
            )
        echo. >>%_CMPLOGFILE%
        echo *** TestQ: !_THIS_TASKNAME! >>%_CMPLOGFILE%
        type %_CMP_OUT%\!_THIS_TASKNAME!\diff\cmp.log >>%_CMPLOGFILE%
    )

) else (

    if not exist %_CMP_OUT%\%_TOPIC%\log md %_CMP_OUT%\%_TOPIC%\log
    if not exist %_CMP_OUT%\%_TOPIC%\diff md %_CMP_OUT%\%_TOPIC%\diff
	
	call %G_TIMESTAMP%
    
    echo %_NMTDRIVER% -compare -writetlog -ticket=%_CMPNMT_TESTQFOLDER%\NDLCompare.ticket -log=%_CMP_OUT%\%_TOPIC%\log -ref=%_REFFOLDER%\%_TOPIC% -out=%_CMP_OUT%\%_TOPIC%\diff %_CMP_IN%\%_TOPIC%\*.pdf
    echo %_NMTDRIVER% -compare -writetlog -ticket=%_CMPNMT_TESTQFOLDER%\NDLCompare.ticket -log=%_CMP_OUT%\%_TOPIC%\log -ref=%_REFFOLDER%\%_TOPIC% -out=%_CMP_OUT%\%_TOPIC%\diff %_CMP_IN%\%_TOPIC%\*.pdf >>%_LOGFILE%
 
    %_NMTDRIVER% -compare -writetlog -ticket=%_CMPNMT_TESTQFOLDER%\NDLCompare.ticket -log=%_CMP_OUT%\%_TOPIC%\log -ref=%_REFFOLDER%\%_TOPIC% -out=%_CMP_OUT%\%_TOPIC%\diff %_CMP_IN%\%_TOPIC%\*.pdf > %_CMP_OUT%\%_TOPIC%\%_TOPIC%_NMTCompare.log

	call %G_TIMESTAMP%

    rem Repeat without -compare to create tlog files
    rem echo %_NMTDRIVER% -ticket=%_CMPNMT_TESTQFOLDER%\NDLCompare.ticket -log=%_CMP_OUT%\%_TOPIC%\log -ref=%_REFFOLDER%\%_TOPIC% -out=%_CMP_OUT%\%_TOPIC%\diff %_CMP_IN%\%_TOPIC%\*.pdf
    rem %_NMTDRIVER% -ticket=%_CMPNMT_TESTQFOLDER%\NDLCompare.ticket -log=%_CMP_OUT%\%_TOPIC%\log -ref=%_REFFOLDER%\%_TOPIC% -out=%_CMP_OUT%\%_TOPIC%\diff %_CMP_IN%\%_TOPIC%\*.pdf

    rem Fake finished testq
    copy /Y %_HELPERSFOLDER%\testq.log %_CMP_OUT%\%_TOPIC% > nul

    echo %_NMTREPORT% -report -outputroot=%_PROCESSEDFOLDER% -reportroot=%_PROCESSEDFOLDER% %_CMP_OUT%\%_TOPIC%
    echo %_NMTREPORT% -report -outputroot=%_PROCESSEDFOLDER% -reportroot=%_PROCESSEDFOLDER% %_CMP_OUT%\%_TOPIC% >>%_LOGFILE%

    %_NMTREPORT% -report -outputroot=%_PROCESSEDFOLDER% -reportroot=%_PROCESSEDFOLDER% %_CMP_OUT%\%_TOPIC% > %_CMP_OUT%\%_TOPIC%\%_TOPIC%_NMTReport.log
    
    REM Replace the NDL Model Test build number by the DeskPack one
    echo xml ed -u "/testqueue/inputfile/build[@number='%_NMTBUILDNUMBER%']/@number" -v "DP_%_FULLNDLBUILDNUMBER%" %_CMP_OUT%\%_TOPIC%\%_TOPIC%.xml
    xml ed ^
    -u "/testqueue/build[@number='%_NMTBUILDNUMBER%']/@number" -v "DP_%_FULLNDLBUILDNUMBER%" ^
    -u "/testqueue/inputfile/build[@number='%_NMTBUILDNUMBER%']/@number" -v "DP_%_FULLNDLBUILDNUMBER%" ^
    %_CMP_OUT%\%_TOPIC%\%_TOPIC%.xml > %_STAT_XMLTMPFILE%
    
    echo copy /Y %_STAT_XMLTMPFILE% %_CMP_OUT%\%_TOPIC%\%_TOPIC%.xml
    copy /Y %_STAT_XMLTMPFILE% %_CMP_OUT%\%_TOPIC%\%_TOPIC%.xml
    
    REM Send the current report to the native NMT storage
    if not exist "%_NMTREPORTROOT%\%_TOPIC%_%_CMP_FOLDERNAME%\%_TOPIC%" md "%_NMTREPORTROOT%\%_TOPIC%_%_CMP_FOLDERNAME%\%_TOPIC%"
    copy /Y %_CMP_OUT%\%_TOPIC%\%_TOPIC%.xml "%_NMTREPORTROOT%\%_TOPIC%_%_CMP_FOLDERNAME%\%_TOPIC%"
    if not exist "%_NMTREPORTROOT%\%_TOPIC%_%_CMP_FOLDERNAME%\%_TOPIC%\diff" md "%_NMTREPORTROOT%\%_TOPIC%_%_CMP_FOLDERNAME%\%_TOPIC%\diff"
    copy /y %_CMP_OUT%\%_TOPIC%\diff\*.diff "%_NMTREPORTROOT%\%_TOPIC%_%_CMP_FOLDERNAME%\%_TOPIC%\diff"

    REM Collect the log files
    for /F "usebackq delims=" %%f in (`dir /b '%_CMP_OUT%\%_TOPIC%\log\*.log'`) do (
        set _THIS_LOGFILE=%%f
        echo --- File : !_THIS_LOGFILE! >>%_PRECMPLOGFILE%
        type "%_CMP_OUT%\%_TOPIC%\log\!_THIS_LOGFILE!" >>%_PRECMPLOGFILE%
        )
    type %_CMP_OUT%\!_THIS_TASKNAME!\diff\cmp.log >>%_CMPLOGFILE%
)

echo xml ed -d "/builds/build[@number='%_NMTBUILDNUMBER%']" "%_PROCESSEDFOLDER%\builddates.xml"
xml ed -d "/builds/build[@number='%_NMTBUILDNUMBER%']" "%_PROCESSEDFOLDER%\builddates.xml" > %_STAT_XMLTMPFILE%
    
copy /Y "%_STAT_XMLTMPFILE%" "%_PROCESSEDFOLDER%\builddates.xml"

REM Add new build to builddates.xml

REM Check presence of the existing build in the list
echo xml sel -t -v "count(/builds/build[@number='DP_%_FULLNDLBUILDNUMBER%'])" "%_PROCESSEDFOLDER%\builddates.xml"
xml sel -t -v "count(/builds/build[@number='DP_%_FULLNDLBUILDNUMBER%'])" "%_PROCESSEDFOLDER%\builddates.xml" > %_STAT_XMLTMPFILE%
set /P _CURRENTBUILSDCOUNT=<%_STAT_XMLTMPFILE%

REM Add only if the current build does not exist in the list
if %_CURRENTBUILSDCOUNT%==0 (
    echo xml ed -s "/builds" -t elem -n build -s "/builds/build[last()]" -t attr -n number -v "DP_%_FULLNDLBUILDNUMBER%" -s "/builds/build[last()]" -t attr -n date -v %_G_TIMESTAMP% %_PROCESSEDFOLDER%\builddates.xml
    xml ed ^
    -s "/builds" -t elem -n build ^
    -s "/builds/build[last()]" -t attr -n number -v "DP_%_FULLNDLBUILDNUMBER%"^
    -s "/builds/build[last()]" -t attr -n date -v %_G_TIMESTAMP%^
    %_PROCESSEDFOLDER%\builddates.xml > %_STAT_XMLTMPFILE%
    copy /Y "%_STAT_XMLTMPFILE%" "%_PROCESSEDFOLDER%\builddates.xml"
)

REM Update the build collection by a new one
copy /Y "%_PROCESSEDFOLDER%\builddates.xml" "%_NMTREPORTROOT%"


call %G_RESTART_NMT%

echo Comparing done.
echo Comparing done. >>%_LOGFILE%

echo %_TOPIC% Pre-compare Render Log File: %_PRECMPLOGFILE%
echo %_TOPIC% Compare Log File: %_CMPLOGFILE%

echo %_TOPIC% Pre-compare Render Log File: %_PRECMPLOGFILE% >>%_LOGFILE%
echo %_TOPIC% Compare Log File: %_CMPLOGFILE% >>%_LOGFILE%


EXIT /B 0
